apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nhn-ingress
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.issuer }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{.Values.nhnTags.ingressPrefix}}(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: nhn-tags
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nhn-common
                port:
                  number: 80

  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: nhn-ingress-cert