apiVersion: apps/v1
kind: Deployment
metadata:
  name: nhn-categories
  labels:
    app: nhn-categories
spec:
  replicas: {{ .Values.categories.replicas }}
  template:
    metadata:
      name: nhn-categories
      labels:
        app: nhn-categories
    spec:
      containers:
        - name: nhn-categories
          env:
            - name: SwaggerPrefix
              value: {{ .Values.categories.ingressPrefix }}
            - name: nhn.MongoDbParameters.ConnectionString
              value: {{ .Values.mongodb.connectionString }}
            - name: nhn.MongoDbParameters.DatabaseName
              value: {{ .Values.mongodb.databaseName }}
            - name: nhn.KafkaParameters.ConnectionString
              value: {{ .Values.kafka.connectionString }}
          image: {{ .Values.categories.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
  selector:
    matchLabels:
      app: nhn-categories
