name: Build NhNCommon

on:
  workflow_dispatch:
    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy
      uses: WyriHaximus/github-action-helm3@v2
      with:
        exec: helm upgrade nhn . --install --wait --atomic --namespace=nhn --create-namespace 
        kubeconfig: '${{ secrets.KUBECONFIG }}'
